### ISSUE TITLE
Color URL doesn't work

### ISSUE THREAD

**Issue by bound-variable** [EECSB/Google-Search-Customizer#2]

**Comment by EECSB** [comment]
Hi. 

When I try to reproduce the issue everything seems to work fine for me. When the "Color URL" is ticked the URLs change color to green otherwise they remain black. Be sure to refresh the page after making changes in the extension settings. 

If the issue still persists could you screenshot the settings in your extension(Maybe it only happens while a specific configuration is applied.)?

**Comment by EECSB** [comment]
I will close this for now, but if any new information is provided feel free to open this issue again.
