### ISSUE TITLE
Remove Perspectives widget support

### ISSUE THREAD

**Issue by eavelardev** [EECSB/Google-Search-Customizer#23]
Like the News widget, another section was added to google search results called Perspectives, so it will be great to consider this in the options.

**Comment by EECSB** [comment]
Hi.

The extension should also work when you select the "Perspectives" section.
It's possible that some things weren't getting removed due to some other bugs that should be fixed now. 
Now I also added an additional option under "Additional Settings" called "Remove video thumbnails from search results" to remove embedded video thumbnails from the search results.
