### ISSUE TITLE
Feature Request: AI Overview

### ISSUE THREAD

**Issue by ericcberg** [EECSB/Google-Search-Customizer#25]
I would appreciate the option to filter out the "AI Overview" now being added to the top of search results.

**Comment by EECSB** [comment]
Hi.

I checked and as it turns out one of the options(Featured Snippet Widget) already does that. 
So if you enable this it should hide the "AI Overview" section:
![ai ov](https://github.com/EECSB/Google-Search-Customizer/assets/50377992/385b7654-484a-4611-b7ca-11d6290fc89a)


I have also updated the text like so for the next release(can take a few days before the update becomes available on the extensions store) to make things clearer.
![ai ov2](https://github.com/EECSB/Google-Search-Customizer/assets/50377992/c5456910-6883-4f0d-9cba-5fcde7d9f306)
