### ISSUE TITLE
Disabled side bar info appears briefly before disappearing

### ISSUE THREAD

**Issue by bound-variable** [EECSB/Google-Search-Customizer#3]

**Comment by EECSB** [comment]
Hi.

Currently, this is the expected behaviour as the extension waits for the page to load then it looks for the specific elements and modifies/removes them. As a result, you see the page load and shortly after the elements disappear.

I will check if there is a way to modify the page before it gets displayed.

**Comment by EECSB** [comment]
I'm not sure how I could edit the page from the content script of the extension before it gets rendered. If someone knows how to solve this they are welcome to leave a suggestion or to contribute the code. I will close the issue for now.
